import type { NextPage } from 'next'
import Head from 'next/head'
import AboutMe from '../component/AboutMe'
import MyPhoto from '../component/myPhoto/MyPhoto'
import Nav from '../component/Nav'
import {useEffect} from 'react'
import s from '../styles/Home.module.scss'
import {useRef} from 'react'
import { useSelector } from 'react-redux'
import { useDispatch } from 'react-redux'
import { saveDataFromApiWork } from '../redux/features/apiWork/apiWork'
import MyProjects from '../component/MyProjects'
import { saveDataMyProjects } from '../redux/features/apiMyProjects/myProjects'
import { DataMyProjects } from './api/MyProjects'
import { DataWork } from './api/workData'
import Contact from '../component/Contact'
import { saveDataMySport } from '../redux/features/apiSport/apiSport'

export const getStaticProps=async()=>{
  const res= await fetch("http://localhost:3000/api/workData")
  const myWork= await res.json()
  const resMyProjects= await fetch("http://localhost:3000/api/MyProjects")
  const myProjects= await resMyProjects.json()
  const resSport=await fetch("http://localhost:3000/api/Sport")
  const Sport=await resSport.json()


  return {
    props:{
      myWork,
      myProjects,
      Sport
    }
  }
}


const Home: NextPage = (props:any) => {

  const dispatch=useDispatch()
  dispatch(saveDataFromApiWork(props.myWork))
  dispatch(saveDataMyProjects(props.myProjects))
  dispatch(saveDataMySport(props.Sport))
 
 

useEffect(()=>{
  window.scrollTo(0,0)
},[])
  return (
    <div className={s.container}>
      <Head>
        <title>Marcin Kalwara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com"/>
<link href="https://fonts.googleapis.com/css2?family=Alumni+Sans+Collegiate+One&family=Bahianita&family=Dancing+Script:wght@500;600&family=Fasthand&family=Inconsolata:wght@200;400&family=Inspiration&family=Pacifico&family=Patrick+Hand&family=Rubik+Distressed&family=Rubik+Glitch&family=Rubik+Microbe&family=Rubik:wght@300&display=swap" rel="stylesheet"/>

        
      </Head>
      
    <nav className={s.nav}>
      <Nav></Nav>

    </nav>
      <main className={s.main}>
        <MyPhoto></MyPhoto>
        <AboutMe ></AboutMe>
        <MyProjects></MyProjects>
      </main>

      <footer className={s.footer}>
       <Contact></Contact>
      </footer>
    </div>
  )
}

export default Home
